#!/bin/bash
if [ $# -ne 5 ]
then
	echo Usage: multi_transit datadir server ra dec tcount
	exit
fi
ra=`python -c "print($3-0.25)"`
dec=$4
receiver_xmlrpc="http://$2:14200"
datadir=$1
tcount=$5
t=0
while [ $t -lt $tcount ]
do
    $HOME/motiontools/xmlrpc_send.py --xmlrpc $receiver_xmlrpc \
       --parameter set_filename --value "/dev/null"
	$HOME/motiontools/carp_motion.py --ra $ra --dec $dec --serror 0.075
	date=`date -u +%Y%m%d`
	$HOME/motiontools/xmlrpc_send.py --xmlrpc $receiver_xmlrpc \
	   --parameter set_filename --value $datadir/$date-transit-$t-doppler.dat
	sleep 1800
	t=`expr $t + 1`
done
