#!/bin/bash
if [ $# -ne 2 ]
then
	echo Usage: sun_dec_scan datadir server
	exit
fi
receiver_xmlrpc="http://$2:14200"
datadir=$1
for offset in -0.5 -0.25 0.0 0.25 0.5
do
    $HOME/motiontools/xmlrpc_send.py --xmlrpc $receiver_xmlrpc \
       --parameter set_filename --value "/dev/null"
	$HOME/motiontools/carp_motion.py --planet Sun --eloffset $offset
	date=`date -u +%Y%m%d`
	$HOME/motiontools/xmlrpc_send.py --xmlrpc $receiver_xmlrpc \
	   --parameter set_filename --value $datadir/$date-$offset-doppler.dat
	sleep 120
done
